### ISSUE TITLE
can you show the code of function: create_pos_enc?

### ISSUE THREAD

**Issue by yanghongbiao** [Garvit-32/Non-Attentive-Tacotron#1]
@Garvit-32 hi. can you show how to create pos_enc_inp in function: create_pos_enc ? thanks.

**Comment by Garvit-32** [comment]
@yanghongbiao This code is not working!  I am trying to fix it.

**Comment by yanghongbiao** [comment]
> @yanghongbiao This code is not working! I am trying to fix it.

thansk, anyway. I will also try.
